//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcGIS_System_Profiler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArcGIS_System_Profiler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closebutton {
            get {
                object obj = ResourceManager.GetObject("closebutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap errorIcon {
            get {
                object obj = ResourceManager.GetObject("errorIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources\help.png.
        /// </summary>
        internal static string helpIcon {
            get {
                return ResourceManager.GetString("helpIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] initialcachesettings {
            get {
                object obj = ResourceManager.GetObject("initialcachesettings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap initIcon {
            get {
                object obj = ResourceManager.GetObject("initIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] item {
            get {
                object obj = ResourceManager.GetObject("item", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ESRI_ItemInformation Culture=&apos;en-AU&apos;&gt;
        ///&lt;name&gt;SystemProfilerTestMapService&lt;/name&gt;
        ///&lt;guid&gt;BCF7E0A3-CF5C-4199-BD03-9169BA905E92&lt;/guid&gt;
        ///&lt;catalogpath&gt;&lt;/catalogpath&gt;
        ///&lt;snippet&gt;Test Map Service for System Profiler app&lt;/snippet&gt;
        ///&lt;description&gt;Test Map Service for System Profiler app&lt;/description&gt;
        ///&lt;summary&gt;Test Map Service for System Profiler app&lt;/summary&gt;
        ///&lt;title&gt;SystemProfilerTestMapService&lt;/title&gt;
        ///&lt;tags&gt;mapserviceTest&lt;/tags&gt;
        ///&lt;type&gt;Service Definition&lt;/type&gt;
        ///&lt;typekeywo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string iteminfo {
            get {
                return ResourceManager.GetString("iteminfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] manifest {
            get {
                object obj = ResourceManager.GetObject("manifest", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;metadata xml:lang=&quot;en&quot;&gt;
        ///&lt;Esri&gt;
        ///&lt;CreaDate&gt;20201104&lt;/CreaDate&gt;
        ///&lt;CreaTime&gt;19572800&lt;/CreaTime&gt;
        ///&lt;ArcGISFormat&gt;1.0&lt;/ArcGISFormat&gt;
        ///&lt;SyncOnce&gt;TRUE&lt;/SyncOnce&gt;
        ///&lt;/Esri&gt;
        ///&lt;dataIdInfo&gt;
        ///&lt;idAbs&gt;Test Map Service for System Profiler app&lt;/idAbs&gt;
        ///&lt;searchKeys&gt;
        ///&lt;keyword&gt;mapserviceTest&lt;/keyword&gt;
        ///&lt;/searchKeys&gt;
        ///&lt;idPurp&gt;Test Map Service for System Profiler app&lt;/idPurp&gt;
        ///&lt;idCredit&gt;&lt;/idCredit&gt;
        ///&lt;resConst&gt;
        ///&lt;Consts&gt;
        ///&lt;useLimit&gt;&lt;/useLimit&gt;
        ///&lt;/Consts&gt;
        ///&lt;/resConst&gt;
        ///&lt;/dataIdInfo&gt;
        ///&lt;Bina [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string metadata {
            get {
                return ResourceManager.GetString("metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon report {
            get {
                object obj = ResourceManager.GetObject("report", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Report_Template {
            get {
                object obj = ResourceManager.GetObject("Report_Template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] serviceconfiguration {
            get {
                object obj = ResourceManager.GetObject("serviceconfiguration", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap successIcon {
            get {
                object obj = ResourceManager.GetObject("successIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SystemProfilerTestMapService {
            get {
                object obj = ResourceManager.GetObject("SystemProfilerTestMapService", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SystemProfilerTestMapService1 {
            get {
                object obj = ResourceManager.GetObject("SystemProfilerTestMapService1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SystemProfilerTestMapService2 {
            get {
                object obj = ResourceManager.GetObject("SystemProfilerTestMapService2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thumbnail {
            get {
                object obj = ResourceManager.GetObject("thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tilingservice {
            get {
                object obj = ResourceManager.GetObject("tilingservice", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
